services:
  frontend:
    image: python:3.10
    ports:
      - "8080:3000"
    volumes:
      - ./python-app:/code
    entrypoint: /bin/bash -c "/code/start.sh 'frontend:start()'"
    working_dir: /code
    environment:
      FLASK_SECRET_KEY: 'uUnOhNnyzElcjAt9CL1R'
  backend:
    image: python:3.10
    ports:
      - "8081:3000"
    volumes:
      - ./python-app:/code
    entrypoint: /bin/bash -c "/code/start.sh 'backend:start()'"
    working_dir: /code
    environment:
      FLASK_SECRET_KEY: 'uUnOhNnyzElcjAt9CL1R'
  redis:
    image: redis/redis-stack
    ports:
      - 8001:8001
      - 6379:6379
    container_name: redis-stack
    volumes:
      - ./local-data:/data
